<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [2]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [4]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print(a.ndim)
print(b.ndim)
# ========
print(a)
print(b)

2
2
[[0.53002284 0.21457586 0.46960803 ... 0.77606524 0.98151604 0.12655207]
 [0.94182832 0.60273388 0.6691278  ... 0.25332698 0.3080745  0.13550312]
 [0.00255142 0.69795902 0.93854011 ... 0.89440087 0.98829763 0.84454519]
 ...
 [0.62821655 0.75246508 0.04083654 ... 0.94870372 0.59180595 0.70844348]
 [0.09167093 0.59565835 0.46093228 ... 0.22153814 0.55799911 0.94676678]
 [0.81643093 0.32712358 0.37576203 ... 0.73937914 0.44649243 0.59195662]]
[[0.45532261 0.36497979 0.71532417 ... 0.44970203 0.21836512 0.58697744]
 [0.88963738 0.87334062 0.88435522 ... 0.26205765 0.55567605 0.41352288]
 [0.51208278 0.72983904 0.11065142 ... 0.89539526 0.07618592 0.26197844]
 ...
 [0.72775691 0.35423571 0.39987262 ... 0.89953859 0.14094383 0.02810743]
 [0.30335789 0.9041608  0.79775626 ... 0.35062905 0.76264554 0.44878827]
 [0.55117868 0.12626571 0.82029376 ... 0.09841258 0.42804311 0.14027103]]


In [25]:
def no_numpy_mult(a, b):
    n,m = len(a), len(a[0])
    k,l = len(b), len(b[0])
    
    result = [[] for i in range(n)]
    
    
    if m != k:
        return None
    
    for i in range(n):
        for r in range(l):
            row_v = []
            for j in range(k):
                row_v.append(b[j][r])
            
            result[i].append(sum(map(lambda x,y : x*y, a[i], row_v)))
        
    
    return result

In [26]:
def numpy_mult(a, b):
    return np.dot(a,b)

In [27]:
%%time
# засечем время работы функции без NumPy
M1 = no_numpy_mult(a, b)

CPU times: user 601 ms, sys: 1.6 ms, total: 602 ms
Wall time: 602 ms


In [8]:
%%time
# засечем время работы функции с NumPy
M2 = numpy_mult(a, b)

CPU times: user 701 µs, sys: 457 µs, total: 1.16 ms
Wall time: 244 µs


In [31]:
M1[0]

[19.80988367894858,
 23.475641226194288,
 28.4442482712892,
 24.219298315564007,
 21.985021102120978,
 22.417889076870445,
 23.737736478894075,
 23.929061743121437,
 21.802977163801405,
 20.142040622295273,
 23.410051755176006,
 22.51141257102992,
 22.25105569218831,
 23.05751285041381,
 23.77945787729509,
 24.843451871078997,
 25.2167539777668,
 25.83115124232371,
 23.661362256613828,
 23.223368668429927,
 21.34262782688091,
 22.791585631256638,
 24.23605029162241,
 20.658672847595565,
 23.81748822025675,
 22.001268433136314,
 21.91990622392316,
 20.447326814330577,
 23.160452238686048,
 23.466191796239624,
 22.91095154456715,
 24.31053038953864,
 25.376616413942685,
 25.249810186332443,
 21.632564341805075,
 23.208811800076617,
 26.014407363541075,
 23.66203373065509,
 23.788692389802563,
 24.90433336640723,
 23.04462590545089,
 25.083495167085175,
 23.16829770652608,
 21.53676047762165,
 22.899675521949955,
 19.918637832877923,
 24.894496169993108,
 23.95582158064011,
 26.6707799279

In [38]:
# проверим корректность
M1

[[19.80988367894858,
  23.475641226194288,
  28.4442482712892,
  24.219298315564007,
  21.985021102120978,
  22.417889076870445,
  23.737736478894075,
  23.929061743121437,
  21.802977163801405,
  20.142040622295273,
  23.410051755176006,
  22.51141257102992,
  22.25105569218831,
  23.05751285041381,
  23.77945787729509,
  24.843451871078997,
  25.2167539777668,
  25.83115124232371,
  23.661362256613828,
  23.223368668429927,
  21.34262782688091,
  22.791585631256638,
  24.23605029162241,
  20.658672847595565,
  23.81748822025675,
  22.001268433136314,
  21.91990622392316,
  20.447326814330577,
  23.160452238686048,
  23.466191796239624,
  22.91095154456715,
  24.31053038953864,
  25.376616413942685,
  25.249810186332443,
  21.632564341805075,
  23.208811800076617,
  26.014407363541075,
  23.66203373065509,
  23.788692389802563,
  24.90433336640723,
  23.04462590545089,
  25.083495167085175,
  23.16829770652608,
  21.53676047762165,
  22.899675521949955,
  19.918637832877923,
  24.8944

In [37]:
list(M2)[0]

array([19.80988368, 23.47564123, 28.44424827, 24.21929832, 21.9850211 ,
       22.41788908, 23.73773648, 23.92906174, 21.80297716, 20.14204062,
       23.41005176, 22.51141257, 22.25105569, 23.05751285, 23.77945788,
       24.84345187, 25.21675398, 25.83115124, 23.66136226, 23.22336867,
       21.34262783, 22.79158563, 24.23605029, 20.65867285, 23.81748822,
       22.00126843, 21.91990622, 20.44732681, 23.16045224, 23.4661918 ,
       22.91095154, 24.31053039, 25.37661641, 25.24981019, 21.63256434,
       23.2088118 , 26.01440736, 23.66203373, 23.78869239, 24.90433337,
       23.04462591, 25.08349517, 23.16829771, 21.53676048, 22.89967552,
       19.91863783, 24.89449617, 23.95582158, 26.67077993, 25.90382231,
       22.76043363, 19.49163361, 21.86300524, 24.35993103, 20.67482462,
       23.22004171, 23.84178961, 23.07553301, 23.53095375, 25.80129165,
       25.58212986, 23.04203471, 22.99454933, 24.4071062 , 23.46743948,
       22.75002197, 23.32406864, 21.92757443, 24.55578979, 25.43

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [39]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.02297575 0.85211994 0.63488726] [0.85807734 0.58453463 0.76619031]


In [49]:
def no_numpy_scalar(a,b):
    return sum(map(lambda x,y : x*y, a,b))

In [50]:
def numpy_scalar(a,b):
    return np.dot(a,b)

In [46]:
%time 
product_1 = scalar_product(a,b)

CPU times: user 3 µs, sys: 1e+03 ns, total: 4 µs
Wall time: 5.96 µs


In [47]:
%time 
product_2 = np_scalar_product(a,b)

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 5.96 µs


In [48]:
# проверим корректность:
np.abs(product_1 - product_2).sum()

0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [64]:
# функция, решающая задачу с помощью NumPy
def diag_2k(a):
    sum_ = 0
    diag = np.diag(a)
    
    sum_ += diag[diag % 2 == 0].sum()
    return sum_

In [65]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 6, 2, 5, 4],
       [2, 3, 9, 6, 9],
       [5, 8, 9, 3, 2],
       [2, 1, 8, 1, 8],
       [9, 8, 5, 1, 8]])

In [66]:
%%time
# засечем время работы функции с NumPy
diag_2k(a)

CPU times: user 66 µs, sys: 7 µs, total: 73 µs
Wall time: 77 µs


12

In [67]:
diag_2k(np.ones((5,5)))

0.0

### Задание 4
​
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$, s_k=x_1+...+x_k, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.


​

​ 

In [89]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):

    result = np.cumsum(A, axis=1)
    return result

In [90]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = cumsum(A)

AxisError: axis 1 is out of bounds for array of dimension 1

In [87]:
A

array([3.04710486e-01, 1.77741899e-02, 9.48432501e-01, 2.83951600e-02,
       7.28176257e-01, 2.43212874e-01, 4.70733802e-01, 8.55666148e-01,
       4.14818751e-01, 9.75265307e-01, 7.77720685e-01, 1.43652031e-01,
       3.88443385e-01, 2.48560502e-01, 8.55207229e-02, 8.88928458e-01,
       1.77537254e-02, 1.36965235e-01, 6.86394765e-01, 9.16579632e-01,
       3.65945694e-01, 7.48093866e-01, 5.67906026e-01, 4.88930952e-01,
       5.99930006e-02, 4.88721404e-01, 9.93886268e-01, 6.53038503e-01,
       7.28190450e-01, 3.51827469e-01, 1.41620170e-01, 6.71377991e-01,
       7.05731216e-02, 1.31360296e-01, 2.35592639e-02, 3.05763268e-01,
       9.83148746e-01, 1.12717897e-01, 4.94192771e-01, 3.45032869e-01,
       8.06767548e-01, 4.91216421e-01, 6.40729849e-01, 2.69173002e-01,
       3.05718222e-01, 9.50749302e-02, 9.28409962e-01, 6.04554583e-01,
       9.05979909e-01, 1.84271352e-01, 5.04075837e-01, 6.93026747e-02,
       5.28128729e-01, 4.59674965e-01, 2.86161067e-01, 5.50882778e-01,
      

In [88]:
S2

array([3.04710486e-01, 3.22484676e-01, 1.27091718e+00, 1.29931234e+00,
       2.02748859e+00, 2.27070147e+00, 2.74143527e+00, 3.59710142e+00,
       4.01192017e+00, 4.98718548e+00, 5.76490616e+00, 5.90855819e+00,
       6.29700158e+00, 6.54556208e+00, 6.63108280e+00, 7.52001126e+00,
       7.53776499e+00, 7.67473022e+00, 8.36112499e+00, 9.27770462e+00,
       9.64365031e+00, 1.03917442e+01, 1.09596502e+01, 1.14485812e+01,
       1.15085742e+01, 1.19972956e+01, 1.29911818e+01, 1.36442203e+01,
       1.43724108e+01, 1.47242382e+01, 1.48658584e+01, 1.55372364e+01,
       1.56078095e+01, 1.57391698e+01, 1.57627291e+01, 1.60684924e+01,
       1.70516411e+01, 1.71643590e+01, 1.76585518e+01, 1.80035846e+01,
       1.88103522e+01, 1.93015686e+01, 1.99422985e+01, 2.02114715e+01,
       2.05171897e+01, 2.06122646e+01, 2.15406746e+01, 2.21452292e+01,
       2.30512091e+01, 2.32354804e+01, 2.37395563e+01, 2.38088589e+01,
       2.43369877e+01, 2.47966626e+01, 2.50828237e+01, 2.56337065e+01,
      

### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [112]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def transform(X, a=1):
    
    def copy_gluing(x):
        x_odd_index = np.copy(x)
        x_odd_index[1::2] = a
        x_odd_index[::2] = x_odd_index[::2] ** 3
        return np.hstack((x, x_odd_index[::-1]))
    
    return np.apply_along_axis(copy_gluing,axis=1,arr=X)
    
    
    

In [115]:
def transform(X, a=1):
    Y = np.copy(X)
    Y[:,1::2] = a
    Y[:,0::2] **= 3
    return np.hstack((X, Y[:,::-1]))

In [116]:
X = np.array([[100,200,300,400,500],[100,200,300,400,500]])

print(X)

# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = transform(X, 5)

[[100 200 300 400 500]
 [100 200 300 400 500]]
CPU times: user 66 µs, sys: 13 µs, total: 79 µs
Wall time: 73 µs


In [118]:
S2

array([[      100,       200,       300,       400,       500, 125000000,
                5,  27000000,         5,   1000000],
       [      100,       200,       300,       400,       500, 125000000,
                5,  27000000,         5,   1000000]])

### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [145]:
# функция, решающая задачу с помощью NumPy
def encode(a):
    
    diff_arr = np.diff(a)
    diff_arr = np.insert(diff_arr, 1, 1)
    
    ind = np.where(diff_arr != 0)[0]
    
    return (a[ind], [len(item) for item in np.split(a, ind)[1:]])

In [119]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [146]:
%time x, num = encode(X)

CPU times: user 141 µs, sys: 14 µs, total: 155 µs
Wall time: 146 µs


In [143]:
x

array([1, 2, 3, 1, 5, 2, 3])

In [144]:
num

[1, 2, 2, 2, 2, 1, 2]

In [120]:
np.unique(X, return_index=True, return_counts=True)

(array([1, 2, 3, 5]), array([0, 1, 3, 7]), array([3, 3, 4, 2]))

In [122]:
len(X)

12

In [123]:
a = np.diff(X)

In [127]:
a = np.insert(a,1,1)

In [131]:
ind = np.where(a != 0)[0]

In [ ]:
X[X[:,]]

In [132]:
X[ind]

array([1, 2, 3, 1, 5, 2, 3])

In [133]:
ind

array([ 0,  1,  3,  5,  7,  9, 10])

In [139]:
np.split(X, ind)

[array([], dtype=int64),
 array([1]),
 array([2, 2]),
 array([3, 3]),
 array([1, 1]),
 array([5, 5]),
 array([2]),
 array([3, 3])]